/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TreeflexMap {
        "content": string;
        "levelThreeFirst": string;
        "levelThreeFirstSecond": string;
        "levelThreeSecondFirst": string;
        "levelThreeSecondSecond": string;
        "levelTwo": string;
        "levelTwoFirst": string;
        "levelTwoSecond": string;
        "nodeColor": string;
        "nodeLevelThreeFirstNumber": number;
        "nodeLevelThreeFirstSecondNumber": number;
        "nodeLevelThreeSecondFirstNumber": number;
        "nodeLevelThreeSecondSecondNumber": number;
        "nodeLevelTwoFifthNumber": number;
        "nodeLevelTwoFirstNumber": number;
        "nodeLevelTwoFourthNumber": number;
        "nodeLevelTwoNumber": number;
        "nodeLevelTwoSecondNumber": number;
        "nodeLevelTwoThirdNumber": number;
        "parent": string;
        "textColor": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTreeflexMapElement extends Components.TreeflexMap, HTMLStencilElement {
    }
    var HTMLTreeflexMapElement: {
        prototype: HTMLTreeflexMapElement;
        new (): HTMLTreeflexMapElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "treeflex-map": HTMLTreeflexMapElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TreeflexMap {
        "content"?: string;
        "levelThreeFirst"?: string;
        "levelThreeFirstSecond"?: string;
        "levelThreeSecondFirst"?: string;
        "levelThreeSecondSecond"?: string;
        "levelTwo"?: string;
        "levelTwoFirst"?: string;
        "levelTwoSecond"?: string;
        "nodeColor"?: string;
        "nodeLevelThreeFirstNumber"?: number;
        "nodeLevelThreeFirstSecondNumber"?: number;
        "nodeLevelThreeSecondFirstNumber"?: number;
        "nodeLevelThreeSecondSecondNumber"?: number;
        "nodeLevelTwoFifthNumber"?: number;
        "nodeLevelTwoFirstNumber"?: number;
        "nodeLevelTwoFourthNumber"?: number;
        "nodeLevelTwoNumber"?: number;
        "nodeLevelTwoSecondNumber"?: number;
        "nodeLevelTwoThirdNumber"?: number;
        "onUpdateSatisfiedEvent"?: (event: CustomEvent<any>) => void;
        "parent"?: string;
        "textColor"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "treeflex-map": TreeflexMap;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "treeflex-map": LocalJSX.TreeflexMap & JSXBase.HTMLAttributes<HTMLTreeflexMapElement>;
        }
    }
}
